start_msg: |
To see the filter breaker information, you need to send one of the following
QrCode - UUID - Vless - Vmess - remark
If you don't know how to get one of these, type /what

help_msg: |
It depends on what software you have installed...
If you don't know how to find it, type /what

channel_msg: |
Dear user, to use the bot, please first subscribe to the following channel 👀 
🆔 @premium_channel_404
and then send the /start command again

not_found: "<b>📍Your account information was not found!</b> \n Are you sure you entered <b>QrCode - UUID - Vless - Vmess - remark</b> correctly? \n If you don't know how to get one of these, type /what... \n I will help you with what software you have installed."
acc_info: 💠 Your service information so far 💠
whatapp_msg: What software are you using?

qrcode: Please send the account link